export const resumeDocument = {
  nameFa: 'المان فتوحی',
  nameEn: 'Elman Fotouhi',
  titleFa: 'کارآموز شبکه و میکروتیک',
  titleEn: 'Network & MikroTik Intern',
  locationFa: 'تبریز، آذربایجان شرقی',
  locationEn: 'Tabriz, East Azerbaijan',
  phone: '0914-815-0089',
  email: 'Elmanfotouhi@gmail.com',
  github: 'https://github.com/elman-ctrl',
  githubLabel: 'github.com/elman-ctrl',
  linkedin: 'https://www.linkedin.com/in/elman-fotouhi/',
  linkedinLabel: 'linkedin.com/in/elman-fotouhi',
  website: 'https://elman-fotouhi.vercel.app/',
  websiteLabel: 'elman-fotouhi.vercel.app',
  focusFa: 'تونل و VPN · روتینگ · فایروال · لینوکس',
  focusEn: 'Tunnels & VPN · Routing · Firewall · Linux',
  objectiveFa:
    'کارآموز شبکه با تجربه عملی در میکروتیک، لینوکس و توسعه مبتنی بر هوش مصنوعی. توانمند در راه‌اندازی معماری تونل، اتوماسیون روتینگ و فایروال، و نوشتن مستندات فنی روشن. به دنبال نقش تمام‌وقت در امنیت شبکه و دواپس هستم.',
  objectiveEn:
    'Networking intern with hands-on MikroTik, Linux, and AI-assisted development experience. Skilled at comparing tunnel architectures, automating routing and firewall work, and writing clear technical docs. Seeking a full-time Network Security Engineering / DevOps path toward Forward Deployed Engineer.',
  skillGroups: [
    {
      fa: 'تونل و VPN',
      en: 'Tunnels & VPN',
      itemsFa: [
        'GRE',
        'EoIP',
        'IPsec',
        'WireGuard',
        'OpenVPN',
        'L2TP/IPsec',
        'PPTP',
        'SSTP',
        'زنجیره تونل چندمرحله‌ای',
      ],
      itemsEn: [
        'GRE',
        'EoIP',
        'IPsec',
        'WireGuard',
        'OpenVPN',
        'L2TP/IPsec',
        'PPTP',
        'SSTP',
        'Multi-stage tunnel chaining',
      ],
    },
    {
      fa: 'روتینگ و فایروال',
      en: 'Routing & Firewall',
      itemsFa: [
        'Policy Routing',
        'Load Balancing (PCC)',
        'Failover',
        'NAT',
        'Hairpin NAT',
        'Port Forwarding',
      ],
      itemsEn: [
        'Policy Routing',
        'Load Balancing (PCC)',
        'Failover',
        'NAT',
        'Hairpin NAT',
        'Port Forwarding',
      ],
    },
    {
      fa: 'پایداری و مانیتورینگ',
      en: 'Resilience & Monitoring',
      itemsFa: ['Netwatch', 'SNMP', 'iperf', 'بکاپ خودکار', 'Disaster Recovery', 'MikroTik API'],
      itemsEn: ['Netwatch', 'SNMP', 'iperf', 'Automated backup', 'Disaster Recovery', 'MikroTik API'],
    },
    {
      fa: 'ابزارها',
      en: 'Tools',
      itemsFa: ['Winbox', 'Claude', 'Cursor', 'مستندسازی فنی'],
      itemsEn: ['Winbox', 'Claude', 'Cursor', 'Technical documentation'],
    },
  ],
  experience: {
    datesFa: 'خرداد ۱۴۰۵ – شهریور ۱۴۰۵',
    datesEn: 'Jun 2026 – Sep 2026',
    titleFa: 'کارآموز شبکه و میکروتیک',
    titleEn: 'Network & MikroTik Intern',
    companyFa: 'رایانش ابری دینا (Dinalabs)',
    companyEn: 'Dina Cloud Computing (Dinalabs)',
    cityFa: 'تبریز',
    cityEn: 'Tabriz',
    stack: [
      'GRE',
      'EoIP',
      'IPsec',
      'WireGuard',
      'OpenVPN',
      'L2TP/IPsec',
      'PCC',
      'NAT',
      'Netwatch',
      'MikroTik API',
    ],
    bulletsFa: [
      'طراحی، پیاده‌سازی و مقایسه فناوری‌های تونل برای ارتباط امن بین‌سایتی.',
      'پیاده‌سازی روتینگ سیاست‌محور، توزیع بار و جابه‌جایی خودکار لینک برای پایداری چندلینکه.',
      'ایمن‌سازی مرز شبکه با فایروال و ترجمه آدرس، سپس اعتبارسنجی عملکرد.',
      'اتوماسیون بکاپ و بازیابی از طریق API میکروتیک.',
      'مشارکت در طراحی و راه‌اندازی پروژه دینا رنتال با ابزارهای هوش مصنوعی و تهیه مستندات فنی.',
    ],
    bulletsEn: [
      'Designed, implemented, and compared GRE, EoIP, IPsec, WireGuard, OpenVPN, L2TP/IPsec, PPTP, and SSTP tunnels for secure site-to-site links.',
      'Implemented Policy Routing, PCC load balancing, and automatic failover for multi-link stability.',
      'Hardened the network edge with firewall, NAT, Hairpin NAT, and port forwarding; validated with Netwatch, SNMP, and iperf.',
      'Automated backups and disaster recovery through the MikroTik API.',
      'Helped design and launch Dina Rental with AI-assisted development and supporting technical documentation.',
    ],
  },
  education: {
    titleFa: 'کارشناسی مهندسی کامپیوتر',
    titleEn: 'B.Sc. Computer Engineering',
    placeFa: 'دانشگاه آزاد اسلامی واحد تبریز',
    placeEn: 'Islamic Azad University, Tabriz Branch',
    extraFa: 'ترم ۳',
    extraEn: 'Semester 3',
  },
  languages: [
    { nameFa: 'فارسی', nameEn: 'Persian', levelFa: 'مادری', levelEn: 'Native' },
    { nameFa: 'ترکی آذربایجانی', nameEn: 'Azerbaijani', levelFa: 'مادری', levelEn: 'Native' },
    { nameFa: 'ترکی استانبولی', nameEn: 'Turkish', levelFa: 'حرفه‌ای', levelEn: 'Professional' },
    { nameFa: 'انگلیسی', nameEn: 'English', levelFa: 'متوسط', levelEn: 'Intermediate' },
  ],
  strengthFa:
    'تسلط عملی روی Winbox و ابزارهای هوش مصنوعی برای تسریع پیکربندی شبکه، تحقیق تسک‌ها و مستندسازی.',
  strengthEn:
    'Hands-on fluency with Claude, Cursor, and Winbox to speed up network configuration, task research, and documentation.',
  pdfHrefFa: '/elman-fotouhi-resume.pdf',
  pdfHrefEn: '/elman-fotouhi-resume-en.pdf',
} as const;

export function resumePdfHref(locale: 'fa' | 'en') {
  return locale === 'en' ? resumeDocument.pdfHrefEn : resumeDocument.pdfHrefFa;
}
